export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'hello': 'hello',
  'menu': 'menu',
  'me': 'me',
  'career': 'career',
  'finance': 'finance',
  'skills': 'skills',
  'housing': 'housing',
  'social': 'social',
  'education': 'education',
  'casino': 'casino',
  'settings': 'settings',
  'day': 'day',
  'unemployed': 'unemployed',
  'software': 'software',
  'medicine': 'medicine',
  'sales': 'sales',
  'military': 'military',
  'music': 'music',
  'job-title-unemployed-1': 'unemployed',
  'job-title-software-1': 'intern',
  'job-title-software-2': 'junior developer',
  'job-title-software-3': 'mid level developer',
  'job-title-software-4': 'senior developer',
  'job-title-software-5': 'lead developer',
  'job-title-software-6': 'software architect',
  'job-title-software-7': 'project manager',
  'job-title-software-8': 'chief technology officer',
  'job-title-software-9': 'chief executive officer',
  'job-title-medicine-1': 'student',
  'job-title-medicine-2': 'medical assistant',
  'job-title-medicine-3': 'nurse\'s assistant',
  'job-title-medicine-4': 'nurse',
  'job-title-medicine-5': 'intern',
  'job-title-medicine-6': 'resident',
  'job-title-medicine-7': 'chief resident',
  'job-title-medicine-8': 'attending',
  'job-title-medicine-9': 'department chair',
  'job-title-medicine-10': 'assistant dean',
  'job-title-medicine-11': 'dean of medical school',
  'job-title-sales-1': 'retail sales trainee',
  'job-title-sales-2': 'retail sales associate',
  'job-title-sales-3': 'retail supervisor',
  'job-title-sales-4': 'store manager',
  'job-title-sales-5': 'district manager',
  'job-title-sales-6': 'regional manager',
  'job-title-sales-7': 'sales director',
  'job-title-sales-8': 'vice president of marketing',
  'job-title-sales-9': 'chief marketing officer',
  'job-title-sales-10': 'chief executive officer',
  'job-title-dishwasher-1': 'dishwasher',
  'job-title-music-1': 'bedroom musician',
  'job-title-music-2': 'busker',
  'job-title-music-3': 'house party performer',
  'job-title-music-4': 'dive bar sound engineer',
  'job-title-music-5': 'dive bar performer',
  'job-title-music-6': 'night club performer',
  'job-title-music-7': 'touring musician',
  'job-title-music-8': 'one hit wonder',
  'job-title-music-9': 'superstar',
  'job-title-music-10': 'GOAT',
  'job-title-military-1': 'private',
  'job-title-military-2': 'corporal',
  'job-title-military-3': 'sergeant',
  'job-title-military-4': 'lieutenant',
  'job-title-military-5': 'captain',
  'job-title-military-6': 'major',
  'job-title-military-7': 'colonel',
  'job-title-military-8': 'general',
  'job-title-education-1': 'substitute teacher',
  'job-title-education-2': 'elementary teacher',
  'job-title-education-3': 'high school teacher',
  'job-title-education-4': 'community college adjunct',
  'job-title-education-5': 'university adjunct',
  'job-title-education-6': 'university professor',
  'job-title-education-7': 'department head',
  'job-title-education-8': 'assistant dean',
  'job-title-education-9': 'dean',
  'job-description-software-1': 'Ah, the lowly intern. You fetch coffee, you take notes, and what little code you do get to write will never see the light of day! Make sure to dress really, really well and try not to cultivate any office crushes - remember, this is your only way into this company (unless you know someone, in which case - why are you here?).',
  'job-description-software-2': 'Congratulations, you made it in! Enjoy the efforts of your anxiety-ridden job search, and try to make a good impression. Your salary can only go up from here, but it all depends on your coding skills - otherwise, you might get banished to QA. :(',
  'job-description-software-3': 'You’re a real person now! Your salary is now at a point that it will support approximately 1.75 hobbies, and you can reasonably be expected to support dependents (cats, children, adult siblings) on it. Time to start thinking about things like a “Savings Account” and “Health Insurance”.\n',
  'job-description-software-4': 'You’re good at what you do, and you’re getting good at leading people - chances are, you’ve also been in the industry for a minute. Now that you’ve got “house money” and a “retirement account,” the real question is what you’re going to do to make sure you complete your career on your schedule. How are you going to compete with these kids and their new ideas? You’ve got to figure out a way to compete, or climb before you can be cut. Those d*mn kids...\n',
  'job-description-software-5': 'You’ve secured your position, and you’ve got a small team of your own. Not leading any projects yet, but you finally feel you’re at a point in your career where you can learn, grow, and focus on quality over quantity of code. Oh, wait. No, you need to complete this next project in six months and the client’s demands are completely unreasonable. And, you are now the one responsible for explaining why the time scales won’t work. Did I mention you’re going to get yelled at a lot? You might need some tums...\n',
  'job-description-software-6': '',
  'job-description-software-7': 'How does it feel to run an office of minions? Do you enjoy the power of imposing deadlines, granting holidays, and handing out CTO-approved bonuses? Does it give you a little rush? Is it even about the coding anymore, or are you just in the rat race to the top of the company now? How many friends did you sabotage to get here, Peter??',
  'job-description-software-8': 'If you’re here because you started the software company, welcome. If you’re here because you worked your way up to it, congratulations! You are now responsible for an entire department’s successes and failures - Have fun trying to protect everything you’ve built from the inadequacies of others!',
  'job-description-software-9': '',
  'job-description-medicine-1': 'You’re in the weeds, buddy. You know nothing, they know everything, and your salary may as well be negative with all these loans. Try not to snap your back with books, find and claim your favorite library table early, and make sure you’ve got a soft mattress at home. Coffee, eye drops, and a gym membership are going to be your best friend throughout this process, as well as the friends you binge-drink with along the way.\n',
  'job-description-medicine-2': '',
  'job-description-medicine-3': '',
  'job-description-medicine-4': 'The days are long, the work is hard, and you need good shoes, my friend. Prepare to be the face of the hospital/clinic you work in - you will check in patients, assist patients, care for patients, be lied to by patients, be yelled at or possibly attacked if they’re on meth, and, in addition to everything else, stand a good chance of interacting with bodily substances on a daily basis. It’s a hard grind, but it’s worth it, right? Saving lives?\n',
  'job-description-medicine-5': 'Look alive, idiot - this isn’t med school anymore, and now your lack of knowledge has consequences. You’re still a first-year trainee, so nobody’s taking you too seriously yet, but if a patient crashes, you’re going to have to take the lead. Scared yet? Well, you haven’t even heard about the 36-hour shifts, the lectures, the board exam, the crippling exhaustion… Welcome to medicine!\n',
  'job-description-medicine-6': '',
  'job-description-medicine-7': 'You are large, in charge, and here for nobody’s sh*t. You know your sh*t, you get your sh*t done, and you keep these sh*tty residents in line. You are securing your future as a tenured teaching doctor/professor, and if nobody stopped your ambition by now, nobody will.',
  'job-description-medicine-8': '',
  'job-description-medicine-9': '',
  'job-description-medicine-10': '',
  'job-description-medicine-11': '',
};
