export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'hello': 'hello',
  'menu': 'menu',
  'me': 'me',
  'career': 'career',
  'finance': 'finance',
  'skills': 'skills',
  'housing': 'housing',
  'social': 'social',
  'education': 'education',
  'casino': 'casino',
  'settings': 'settings',
  'day': 'day',
  'intern': 'intern',
  'junior developer': 'junior developer',
  'mid level developer': 'mid level developer',
  'senior developer': 'senior developer',
  'lead developer': 'lead developer',
  'software architect': 'software architect',
  'project manager': 'project manager',
  'chief technology officer': 'chief technology officer',
  'chief executive officer': 'chief executive officer',
  'job-description-software-1': 'Ah, the lowly intern. You fetch coffee, you take notes, and what little code you do get to write will never see the light of day! Make sure to dress really, really well and try not to cultivate any office crushes - remember, this is your only way into this company (unless you know someone, in which case - why are you here?).',
  'job-description-software-2': 'Congratulations, you made it in! Enjoy the efforts of your anxiety-ridden job search, and try to make a good impression. Your salary can only go up from here, but it all depends on your coding skills - otherwise, you might get banished to QA. :(',
  'job-description-software-4': 'You’re a real person now! Your salary is now at a point that it will support approximately 1.75 hobbies, and you can reasonably be expected to support dependents (cats, children, adult siblings) on it. Time to start thinking about things like a “Savings Account” and “Health Insurance”.\n',
  'job-description-software-5': 'You’re good at what you do, and you’re getting good at leading people - chances are, you’ve also been in the industry for a minute. Now that you’ve got “house money” and a “retirement account,” the real question is what you’re going to do to make sure you complete your career on your schedule. How are you going to compete with these kids and their new ideas? You’ve got to figure out a way to compete, or climb before you can be cut. Those d*mn kids...\n',
  'job-description-software-6': 'You’ve secured your position, and you’ve got a small team of your own. Not leading any projects yet, but you finally feel you’re at a point in your career where you can learn, grow, and focus on quality over quantity of code. Oh, wait. No, you need to complete this next project in six months and the client’s demands are completely unreasonable. And, you are now the one responsible for explaining why the time scales won’t work. Did I mention you’re going to get yelled at a lot? You might need some tums...\n',
  'job-description-software-7': '',
  'job-description-software-8': 'How does it feel to run an office of minions? Do you enjoy the power of imposing deadlines, granting holidays, and handing out CTO-approved bonuses? Does it give you a little rush? Is it even about the coding anymore, or are you just in the rat race to the top of the company now? How many friends did you sabotage to get here, Peter??',
  'job-description-software-9': 'If you’re here because you started the software company, welcome. If you’re here because you worked your way up to it, congratulations! You are now responsible for an entire department’s successes and failures - Have fun trying to protect everything you’ve built from the inadequacies of others!',
  'job-description-software-10': '',
};
